<?php
namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $silhouetteMap = [
            'Slips'     => 'slip',
            'Tops'      => 'crop',
            'Outerwear' => 'jacket',
            'Sets'      => 'set',
        ];

        $products = [
            [
                'slug'    => 'halo-slip',
                'name'    => 'The Halo Slip',
                'price'   => 3499,
                'cat'     => 'Slips',
                'palette' => ['#FF5A2C', '#F08A8B', '#EFA0BA'],
                'accent'  => '#D7A8E8',
                'tag'     => 'Featured',
                'sub'     => 'Bias-cut viscose, gradient dyed',
                'sizes'   => ['XS', 'S', 'M', 'L'],
                'drop'    => '04',
                'story'   => 'Cut on the bias from a whisper-weight viscose, the Halo Slip follows the body the way light follows water.',
                'details' => '100% Viscose. Bias cut. Hand-finished hem. Available in Solar Bloom gradient.',
                'care'    => 'Hand wash cold. Dry flat. Do not wring.',
                'fit'     => 'True to size. 32" length from waist.',
            ],
            [
                'slug'    => 'neon-bloom',
                'name'    => 'Neon Bloom',
                'price'   => 3499,
                'cat'     => 'Tops',
                'palette' => ['#EFA0BA', '#D7A8E8', '#E8C0F0'],
                'accent'  => '#FF5A2C',
                'tag'     => 'New',
                'sub'     => 'Cropped silk-blend, gradient print',
                'sizes'   => ['XS', 'S', 'M', 'L', 'XL'],
                'drop'    => '04',
                'story'   => 'A crop that catches light from every angle. Silk-blend fabric with our signature gradient print.',
                'details' => '70% Silk 30% Polyester. Cropped length. Hidden zip closure.',
                'care'    => 'Dry clean only.',
                'fit'     => 'Cropped. Size up for relaxed fit.',
            ],
            [
                'slug'    => 'soft-riot',
                'name'    => 'Soft Riot',
                'price'   => 2899,
                'cat'     => 'Tops',
                'palette' => ['#F08A8B', '#EFA0BA', '#FF5A2C'],
                'accent'  => '#E8C0F0',
                'tag'     => null,
                'sub'     => 'Off-shoulder cotton gauze',
                'sizes'   => ['XS', 'S', 'M', 'L'],
                'drop'    => '04',
                'story'   => 'An off-shoulder top in the softest cotton gauze. Effortless for the day, electric at night.',
                'details' => '100% Cotton gauze. Off-shoulder cut. Elasticated neckline.',
                'care'    => 'Machine wash cool. Tumble dry low.',
                'fit'     => 'Oversized. Size down for fitted look.',
            ],
            [
                'slug'    => 'velvet-mango',
                'name'    => 'Velvet Mango',
                'price'   => 3799,
                'cat'     => 'Outerwear',
                'palette' => ['#FF5A2C', '#F08A8B', '#E8C0F0'],
                'accent'  => '#D7A8E8',
                'tag'     => 'Limited',
                'sub'     => 'Cropped velvet jacket, contrast lining',
                'sizes'   => ['XS', 'S', 'M', 'L'],
                'drop'    => '04',
                'story'   => 'A cropped velvet jacket with contrast lining. Structured enough to be serious, vibrant enough to be fun.',
                'details' => 'Shell: 100% Velvet. Lining: 100% Silk. Cropped length. Single-breasted.',
                'care'    => 'Dry clean only.',
                'fit'     => 'Slightly cropped. True to size.',
            ],
            [
                'slug'    => 'disco-petal',
                'name'    => 'Disco Petal',
                'price'   => 2499,
                'cat'     => 'Sets',
                'palette' => ['#EFA0BA', '#F08A8B', '#D7A8E8'],
                'accent'  => '#FF5A2C',
                'tag'     => null,
                'sub'     => 'Two-piece jersey co-ord',
                'sizes'   => ['XS', 'S', 'M', 'L', 'XL'],
                'drop'    => '04',
                'story'   => 'A jersey two-piece that moves as one. Crop top and high-waist shorts in our coral gradient.',
                'details' => '95% Cotton 5% Elastane jersey. Co-ord set. Crop top + shorts.',
                'care'    => 'Machine wash cool. Reshape and dry flat.',
                'fit'     => 'Relaxed. True to size.',
            ],
            [
                'slug'    => 'tangerine-daze',
                'name'    => 'Tangerine Daze',
                'price'   => 3199,
                'cat'     => 'Slips',
                'palette' => ['#FF5A2C', '#F08A8B', '#EFA0BA'],
                'accent'  => '#E8C0F0',
                'tag'     => null,
                'sub'     => 'Mini slip, sunset wash',
                'sizes'   => ['XS', 'S', 'M', 'L'],
                'drop'    => '04',
                'story'   => 'Our shortest slip, cut in sunset-washed satin. Mini length for maximum impact.',
                'details' => '100% Polyester satin. Mini length. Adjustable straps. Slight stretch.',
                'care'    => 'Hand wash cold. Hang to dry.',
                'fit'     => 'Mini length. True to size.',
            ],
            [
                'slug'    => 'lilac-pulse',
                'name'    => 'Lilac Pulse',
                'price'   => 2799,
                'cat'     => 'Tops',
                'palette' => ['#D7A8E8', '#E8C0F0', '#EFA0BA'],
                'accent'  => '#FF5A2C',
                'tag'     => 'Restock',
                'sub'     => 'Stretch satin bodysuit',
                'sizes'   => ['XS', 'S', 'M', 'L'],
                'drop'    => '04',
                'story'   => 'A stretch satin bodysuit in lilac that snaps shut and holds its shape all night.',
                'details' => '92% Polyester 8% Elastane. Snap closure. Bodysuit silhouette. Square neck.',
                'care'    => 'Machine wash cool. Drip dry.',
                'fit'     => 'Fitted. True to size.',
            ],
            [
                'slug'    => 'cherry-halo',
                'name'    => 'Cherry Halo',
                'price'   => 3599,
                'cat'     => 'Outerwear',
                'palette' => ['#F08A8B', '#EFA0BA', '#FF5A2C'],
                'accent'  => '#D7A8E8',
                'tag'     => null,
                'sub'     => 'Bomber with printed twill',
                'sizes'   => ['XS', 'S', 'M', 'L', 'XL'],
                'drop'    => '04',
                'story'   => 'A bomber jacket in printed twill with ribbed cuffs and hem. Statement piece, easy wear.',
                'details' => '100% Polyester twill. Ribbed cuffs/hem. Zip front. Inner pocket.',
                'care'    => 'Machine wash warm. Hang to dry.',
                'fit'     => 'Relaxed fit. Size down for slim look.',
            ],
            [
                'slug'    => 'cosmic-sorbet',
                'name'    => 'Cosmic Sorbet',
                'price'   => 2999,
                'cat'     => 'Sets',
                'palette' => ['#E8C0F0', '#D7A8E8', '#EFA0BA'],
                'accent'  => '#FF5A2C',
                'tag'     => null,
                'sub'     => 'Knit skirt set',
                'sizes'   => ['XS', 'S', 'M', 'L'],
                'drop'    => '04',
                'story'   => 'A knit two-piece in sherbet tones. Ribbed texture, easy silhouette.',
                'details' => '60% Cotton 40% Acrylic knit. Crop top + midi skirt. Ribbed texture.',
                'care'    => 'Hand wash cold. Reshape and dry flat.',
                'fit'     => 'Relaxed. True to size or size up.',
            ],
            [
                'slug'    => 'sun-spell',
                'name'    => 'Sun Spell',
                'price'   => 4299,
                'cat'     => 'Outerwear',
                'palette' => ['#FF5A2C', '#E8C0F0', '#D7A8E8'],
                'accent'  => '#F08A8B',
                'tag'     => 'New',
                'sub'     => 'Long panelled coat',
                'sizes'   => ['XS', 'S', 'M', 'L'],
                'drop'    => '04',
                'story'   => 'A long panelled coat in contrast blocking. The signature piece of Drop 04.',
                'details' => 'Shell: 70% Wool 30% Polyester. Panelled construction. Longline. Belt included.',
                'care'    => 'Dry clean only.',
                'fit'     => 'Longline. Size up for oversized look.',
            ],
            [
                'slug'    => 'orchid-flame',
                'name'    => 'Orchid Flame',
                'price'   => 3299,
                'cat'     => 'Slips',
                'palette' => ['#D7A8E8', '#E8C0F0', '#FF5A2C'],
                'accent'  => '#F08A8B',
                'tag'     => null,
                'sub'     => 'Maxi slip, gradient dyed',
                'sizes'   => ['XS', 'S', 'M', 'L', 'XL'],
                'drop'    => '04',
                'story'   => 'A gradient-dyed maxi slip that pools at the floor. Floor length, bias cut, unforgettable.',
                'details' => '100% Viscose. Maxi length. Bias cut. Hand-finished hem. Adjustable straps.',
                'care'    => 'Hand wash cold. Dry flat.',
                'fit'     => 'True to size. 58" length from shoulder.',
            ],
            [
                'slug'    => 'sherbet-blazer',
                'name'    => 'Sherbet Blazer',
                'price'   => 4599,
                'cat'     => 'Outerwear',
                'palette' => ['#EFA0BA', '#D7A8E8', '#F08A8B'],
                'accent'  => '#FF5A2C',
                'tag'     => null,
                'sub'     => 'Boyfriend blazer, pastel stripe',
                'sizes'   => ['XS', 'S', 'M', 'L'],
                'drop'    => '04',
                'story'   => 'An oversized boyfriend blazer in pastel stripe. Pair with everything. Steal the room.',
                'details' => '55% Cotton 45% Polyester stripe. Boyfriend fit. Two patch pockets. Lined.',
                'care'    => 'Dry clean only.',
                'fit'     => 'Oversized. Size down for structured look.',
            ],
        ];

        foreach ($products as $data) {
            Product::create(array_merge($data, [
                'brand'      => 'lava',
                'active'     => true,
                'silhouette' => $silhouetteMap[$data['cat']] ?? null,
            ]));
        }
    }
}
